Update deploy_agent.py
Open telemetry causes error with currently used python packages. Have to disable for gsp542 to work at August 6 launch.

Otherwise you will get error, task 5, step 2 upon deployment of the agent.

Traceback (most recent call last):
File "/home/student_02_41e19308915a/agent-security-lab/src/mortgage-agent/deploy_agent.py", line 709, in
main()
File "/home/student_02_41e19308915a/agent-security-lab/src/mortgage-agent/deploy_agent.py", line 673, in main
engine = client.agent_engines.update(name=reasoning_engine_name, agent=app, config=deploy_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/student_02_41e19308915a/.local/lib/python3.12/site-packages/vertexai/_genai/agent_engines.py", line 2824, in update
raise RuntimeError(f"Failed to update Agent Engine: {operation.error}")
RuntimeError: Failed to update Agent Engine: {'code': 3, 'message': 'Reasoning Engine resource [projects/525884312903/locations/us-central1/reasoningEngines/5126135964191686656] failed to start and cannot serve traffic. Please refer to our troubleshooting pages (e.g., https://docs.cloud.google.com/gemini-enterprise-agent-platform/troubleshooting/agent-deployment) to debug and fix the error.'}